os:
  - linux
  - osx
language: python
python:
  - 3.6
before_install:
  - sudo apt-get install python3-sphinx
install:
  - pip install -r requirements.txt
script:
  - pytest
  # after_success:
  - bin/gendocs.sh